language: python
python:
  - 2.7
  - 3.4
  - 3.5

# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
    - pip install coveralls
    - pip install -r requirements.txt
    - pip install -r requirements_dev.txt
script:
    - flake8
    - coverage run --source pylleida setup.py test
after_success:
    - coveralls
